version: "3.8"
services:
  temptaking:
    build:
      context: ./
      dockerfile: Dockerfile
    image: temptaking:1.0
    logging:
      driver: json-file
    volumes:
    - "./data:/app/data"
    container_name: "temptaking_bot"

